import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; // Pastikan baris ini ada jika Anda pakai css bawaan Next.js

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* Script Cloudflare Turnstile Anti-Spam */}
      <Script
        src="https://challenges.cloudflare.com/turnstile/v0/api.js"
        strategy="afterInteractive"
      />

      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
